### ISSUE TITLE
VGG to Mobilenetv2 network

### ISSUE THREAD

**Issue by hardik0** [duongntbk/age_estimator_model#14]
Hey @duongntbk ,
How can I change VGG network to Mobilenetv2 network especially in age_model.py

**Comment by duongntbk** [comment]
Hi hardik0,
Please reference the [Train gender prediction model](https://github.com/duongntbk/age_estimator_model#train-gender-prediction-model) section, especially the code snippet under *Create an object of class GenderModel and use it to create model for feature extraction*.

To use MobiuleNetV2 instead of VGG, the code looks something like this.
```
from keras.applications import MobileNetV2
from gender_model import GenderModel

base = MobileNetV2(include_top=False, weights='imagenet', input_shape=(150, 150, 3))
bm = GenderModel(conv_base=base, num_gpus=2)
```

However, keep in mind that I created this repo more than 2 years ago, it's possible that things have changed since then.

**Comment by hardik0** [comment]
it's working,  thanks!
